### ISSUE TITLE
[FEATURE] Improve how UI jumps around when deleting a playlist

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#84] opened 2024-05-25 15:03 UTC
Reported this one before.

See the gif. Deleting a playlist the UI scroll jumps about. This may be true for other actions. (Edit: happens when playlists are dup'd)

Font size is 13 if that has any bearing on this bug.

![2024 05 25 (16-00-01)](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/44b5ac96-782e-4e9b-8a8c-f45d51683c94)

**Comment by regorxxx** [comment] 2024-05-26 23:45
Jump is intentional since the entire tree is rebuilt and tries to center the last selected/highlighted playlist on current view after refreshing. This is not a bug. You may find it annoying and I could offer a setting to disable it or tweak it to try to maintain the position in some cases, but not a bug.

**Comment by regorxxx** [comment] 2024-05-27 00:05
Closing it since is not a bug, BUT I'm open for feedback about improving it and will appreciate if you test it (and report it here) in a few days after I tweak how it works.

**Closed** 2024-05-27 21:16 UTC
Labels: enhancement
