### ISSUE TITLE
[BUG] Random crash

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#66] opened 2023-07-18 22:30 UTC
**Describe the bug**
I have no idea what caused this. I believe it happened twice now, but I didn't read the error report the first time. I'll try to provide reproduction steps if it happens again.

```
Error: Spider Monkey Panel v1.6.1 ({724C4569-4C15-4E4A-B512-0547946F0D1D}: Playlist Manager v0.5.0-beta25 by XXX)
this.data[z] is undefined

File: playlist_manager_list.js
Line: 1342, Column: 21
Stack trace:
  _list/this.lbtn_up@playlist_manager_list.js:1342:21
  @playlist_manager.js:501:9
  fireEvents/</<@callbacks_xxx.js:149:37
  fireEvents/<@callbacks_xxx.js:145:30

```

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Browser: Wine browser
 - Version: git clone latest

**Comment by sonofevil** [comment] 2023-07-18 22:39
There we go, identical error. I simply double-clicked on an UI-only playlist.

**Comment by regorxxx** [comment] 2023-07-20 22:45
Can't reproduce it, although I can bypass the crash, but I would prefer to find the root of the problem.

Send a gif, and your current settings (filter, sorting).

**Comment by sonofevil** [comment] 2023-07-23 22:41
I can't reproduce it anymore, even though I don't think I changed anything. Maybe some weird memory issue that went away after a restart. I'll have to wait and see if it happens again in the next few days. If not then this is probably safe to close.

**Comment by regorxxx** [comment] 2023-08-01 21:41
Closing it; feel free to report if it happens again.

**Closed by regorxxx** 2023-08-01 21:41 UTC
Labels: bug
