### ISSUE TITLE
[BUG] Folders disappeared after 0.14 update

### ISSUE THREAD

**Issue by WagnerGFX** [regorxxx/Playlist-Manager-SMP#80] opened 2024-03-15 15:35 UTC
### Describe the bug
After updating to 0.14 all folders disappeared and any newly created folders disappear after restarting Foobar.
Disabling and re-enabling the folders feature did not change this behavior.

Returning to v0.13 I've had to recreate all folders again, but they still hold after restarting.

### To Reproduce
1. Create 1 or more folders
2. Add 1 or more playlist to it
3. Restart Foobar2000
4. All playlists are back to being listed with no folders

### Expected behavior
Folder structure should hold between restarts and version updates (if possible).

### System Info
 - Windows 10 x64 22H2
 - Browser: Firefox 123.0.1 (but why?)
 - Foobar2000 v1.6.16
 - Playlist Manager v0.14

### Additional context
I've added the exported properties of the component, in case it helps.

[props v0.14.json](https://github.com/regorxxx/Playlist-Manager-SMP/files/14617629/props.v0.14.json)

**Comment by regorxxx** [comment] 2024-03-16 09:11
According to your properties, folders are disabled. Go to features and restore defaults, and enable them again.

I have not been able to reproduce your bug.

**Comment by regorxxx** [comment] 2024-03-16 11:00
I'm not able to reproduce it with your steps. Have tried multiple times.
You don't need to restart foobar, just restart the panel to test it. (it should behave the same)

Folders are only lost when switching lite mode, which was intended. And I think that's what you did. Anyway that is now changed on the new nightly.

1. Could you confirm that's what you did? (switching lite mode, then restarting)
2. Try new nightly.
3. If that's not the problem, please send me a gif/video or try the same steps on a new blank panel.

**Comment by WagnerGFX** [comment] 2024-03-16 16:15
> You don't need to restart foobar, just restart the panel to test it. (it should behave the same)

I'm not sure on how to do that, as there is no Reload button when right-clicking. I've been even considering opening a request to add Reload and Configure Panel to the settings menu.

>     1. Could you confirm that's what you did? (switching lite mode, then restarting)

I did change the folder and lite settings to see if it would fix the bug, but that was after having all folders disappearing.

Now I've tried:
- Clearing the settings to default
- Uninstalling the whole package and then re-installing it
- The nightly build

But the folders are still disappearing.


Here are 2 videos I recorded using both versions. They are using all the default settings:
- [Video: v0.13](https://drive.google.com/file/d/1e-m168DsNnossY45plcaz5_DgB-O44PW/view?usp=drive_link)
- [Video: v0.14](https://drive.google.com/file/d/1YB0tprin8PoQCe2tvcy4UMeqkRowwdRP/view?usp=drive_link)

One thing I've noticed in 0.14 and nightly is that the panel take some time loading when I start Foobar, this was not happening in 0.13.

**Comment by regorxxx** [comment] 2024-03-16 16:51
> I'm not sure on how to do that, as there is no Reload button when right-clicking. I've been even considering opening a request to add Reload and Configure Panel to the settings menu.

That will never happen. You are missing the native SMP menu when Shift + R. Clicking on any SMP panel, which is the way to manage any panel.

> One thing I've noticed in 0.14 and nightly is that the panel take some time loading when I start Foobar, this was not happening in 0.13.

I think you are missing reading the changelog before updating ;) Configure as needed.

**Comment by regorxxx** [comment] 2024-03-16 18:23
I can't reproduce your problem no matter what I do. 

1. Try the newest nightly which fixed some usage related to folders when using menus (with drag n' drop it was fine).
2. Try reloading the panel instead of restarting foobar2000 and check if it does the same.
3. Does it happen after you set the panel name?
![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/81820764-0a9f-4e90-b41b-858fc57485c4)

**Comment by WagnerGFX** [comment] 2024-03-16 18:39
> That will never happen. You are missing the native SMP menu when Shift + R. Clicking on any SMP panel, which is the way to manage any panel.

I wish this was on the first page of SMP's Docs. WIN+SHIFT+RCLICK was not a shortcut I expected to even exist. 😅
Thank you for the info, it will also make reloading my custom scripts much easier now.

> I think you are missing reading the changelog before updating ;) Configure as needed.

I did read about delays, but every time I try to change it, there is an error, and it returns to the default values.

![error](https://github.com/regorxxx/Playlist-Manager-SMP/assets/16827309/66efadb4-dc8d-418b-8d26-1d411477506f)
_I tried to change it to 1000, but even opening it and pressing OK with the same values throws the error. This might be a separate issue though._

> I will need some time investigating your issue.

Some extra info:
- When I reload the panel, the folder stay in place, the issue is specific to restarting Foobar2000.
- Reverting the .old js_data settings and reloading the panel "fixes" it, but restarting still breaks the folders again.
- The file is still normal after closing Foobar, it only changes after reopening it.

> * Try the newest nightly which fixed some usage related to folders when using menus (with drag n' drop it was fine).
> * Try reloading the panel instead of restarting foobar2000 and check if it does the same.
> * Does it happen after you set the panel name?

Using the newest nightly and changing the panel name did not fix the issue, unfortunately.
Reload is as stated above.

I've added the js_data from 0.13 and 0.14 right after the issue happened. Maybe it can provide some extra insight.
Maybe some bad data from my playlists is forcing the code to throw away the previous data. 🤔
[js_data.zip](https://github.com/regorxxx/Playlist-Manager-SMP/files/14624719/js_data.zip)

Also, this is a list of the components I use, in case there is anything that could interfere (like JSplitter):
![Components](https://github.com/regorxxx/Playlist-Manager-SMP/assets/16827309/c720f982-c55e-4c07-80e3-e8e0ff3ff52e)

**Comment by regorxxx** [comment] 2024-03-16 19:45
> I wish this was on the first page of SMP's Docs. WIN+SHIFT+RCLICK was not a shortcut I expected to even exist. 😅
> Thank you for the info, it will also make reloading my custom scripts much easier now.

I'm not sure where I saw it, but you are right; I have not been able to find it now at SMP docs but I will add it at my wiki and readme PDF then.

>  I tried to change it to 1000, but even opening it and pressing OK with the same values throws the error. This might be a separate issue though.
It's another issue. Fixed now (so you can set delays to zero if desired)

**Comment by regorxxx** [comment] 2024-03-16 19:49
> When I reload the panel, the folder stay in place, the issue is specific to restarting Foobar2000.

I was somehow suspecting that, since most of my tests were reloading. BUT I have not been able to reproduce it restarting foobar yet.

> The file is still normal after closing Foobar, it only changes after reopening it.

So you are saying that after closing foobar, the json file contains your folder? And then when starting it again this is deleted?
![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/d084d6ce-e3bd-479f-a049-7efea35b1eb1)

Will try more tests, maybe I introduced some bug on last release while changing the entire init process.

**Comment by WagnerGFX** [comment] 2024-03-16 21:36
> I'm not sure where I saw it, but you are right; I have not been able to find it now at SMP docs but I will add it at my wiki and readme PDF then.

Yes, please! ❤

> So you are saying that after closing foobar, the json file contains your folder? And then when starting it again this is deleted?

Exactly. Just after opening foobar, I see the file being copied as ".old" and shrinking is size after. At that moment, all folders were deleted from the json.

> Will try more tests, maybe I introduced some bug on last release while changing the entire init process.

If you have some builds available from changes between v0.13 and v0.14, then I can try to narrow it down, in case the changes were made across multiple commits.

**Comment by regorxxx** [comment] 2024-03-16 22:26
Ok, for some reason I was not able to reproduce it with my settings, but I was able to do it in a new panel. It seems the problem is related to delaying playlist loading at startup. Foobar loads the playlists and then it triggers an autosave on the panel so it overwrites the file -with just the UI playlists- before loading it (with the folders).

**Comment by regorxxx** [comment] 2024-03-16 22:32
Let me know if it's fixed for you too (and restore your old js data which should work fine now).

**Closed** 2024-03-16 22:31 UTC
Labels: bug

**Comment by WagnerGFX** [comment] 2024-03-16 23:32
> Let me know if it's fixed for you too (and restore your old js data which should work fine now).

It's fixed! 🥳

> EDIT: this issue has also pointed me to other points where the script was expecting something but the loading was delayed, it affected for ex. at first setup, where the panel would show an empty list with the filter button being active instead of all UI playlists. All this has also been fixed.

I did notice the filter was starting enabled with empty result when resetting the settings, but wasn't sure if it was default behavior.

Another issue I saw was the filter results not showing after restarting, it's also fixed.
